### ISSUE TITLE
怎么禁止访问某个目录如runtime和某后缀文件如.log

### ISSUE THREAD

**Issue by xingline** [ddonline/nginx-lua-waf#1]
请问：禁止访问某个目录如runtime和某后缀文件如.log，写在那个配置文件里，怎么写，求个demo，谢谢！（原本nginx配置也可以，但我想加在waf里）

**Comment by ddonline** [comment]
写到url.rule里面。
如果仅针对某个特定的vhost，比如hostname 为 demo，那么可以这么写：
`^demo-/runtime  或者^demo-/runtime.*`
`^demo-.*\.log`
如果对所有vhost均做限制，则可以这么写：
`/runtime  或者/runtime.* `
`.*\.log 或者\.log`
使用的是正则表达式，你可以在这里测试正则表达式是否正确：http://tool.chinaz.com/regex

**Comment by xingline** [comment]
好的，非常感谢！
