### ISSUE TITLE
如果是多个网站，怎么设置只开启对应域名的防御

### ISSUE THREAD

**Issue by tonyisnewhuman** [ddonline/nginx-lua-waf#2]
服务器有多个域名网站（vhost），怎么设置只针对指定域名进行检测（非具体规则），没有设置的直接跳过检测。
可以把 access_by_lua_file /usr/local/openresty/nginx/conf/nginx-lua-waf/access.lua; 这句只加入对应vhost配置server 下吗？是否影响使用或性能？

**Comment by ddonline** [comment]
1、waf可以对特定的vhost产生影响
waf.lua文件中的函数为具体处理函数，例如下面这个处理IP黑名单的函数，先判断该功能是否开启，再获取规则，然后在组装待匹配项时，拼接了站点的名称ngx.var.server_name，所以说，如果规则中写了具体的站点，那么仅对特定站点起作用，若未指定特定站点，则对所有站点起作用。
`function _M.black_ip_check()`
`    if config.config_black_ip_check == "on" then`
`        local IP_BLACK_RULE = _M.get_rule('blackip.rule')`
`        local BLACK_IP = ngx.var.server_name.."-"..util.get_client_ip()`
2、不建议将access_by_lua_file放到特定站点，因为有些功能是全局的，可能会产生不可预知的情况
3、对性能有一定影响，但lua性能非常高，几乎可以忽略
