### ISSUE TITLE
请问，我有多个站点，但是某个站点有下载.zip文件的需求

### ISSUE THREAD

**Issue by xingline** [ddonline/nginx-lua-waf#3]
请问，我有多个站点，但是某个站点有下载.zip文件的需求，但是waf又全部禁止，请问怎么办？
能否让某个域名或者路径 有权限下载？
比如下载目录为 http://xxx.com/xiazai/(x.zip)
请问该在waf的哪个文件写什么，求demo谢谢

**Comment by ddonline** [comment]
根据处理函数的执行流程，先是URL白名单，然后是URL过滤，所以，你可以先在URL白名单中设置该站点/xiazai/*.zip为允许，然后在URP过滤中设禁止所有*.zip，这样就可以达到你的要求

**Comment by ddonline** [comment]
请参看Nginx Lua WAF处理流程图

**Comment by xingline** [comment]
好的非常感谢

**Comment by xingline** [comment]
我的某个站点无法上传图片（其他没问题），我查看了waf找到了（post.rule和cookie.rule）含有layer，该站用的刚好是layui框架，把waf里的layui都删除，还是无法保存，您知道是什么原因吗？谢谢（保存位置在xxx.com/public/up/下面）

**Comment by ddonline** [comment]
首先可以关闭waf查看是否可正常上传，排除文件系统权限问题；若确为waf阻挡，可以查看waf的日志，里面会记录阻挡原因和对应的规则详情

**Comment by xingline** [comment]
{"timestamp":"2018-09-05T20:11:41+08:00","realip":"45.75.65.5","ruletag":"<(iframe|script|body|img|div|meta|style|base|object|input)",  没毛病啊，服务器上的其他网站不受影响的
